services:
  app:
    build:
      context: .
    image: app
    container_name: app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
