services:
  app:
    build:
      context: .
    image: app
    container_name: app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uv", "run", "main.py"]
