services:
  app:
    build:
      context: .
    image: app
    container_name: app
    depends_on: []
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uv", "run", "src/main.py"]
